### ISSUE TITLE
安装时环境提示都是绿色的，但是到第四步就500错误，帮忙看看谢谢

### ISSUE THREAD

**Issue by xingline** [wisp-x/lsky-pro#119]
2020/04/21 05:20:45 [alert] 6782#0: *12 open socket #6 left in connection 5
2020/04/21 05:20:45 [alert] 6782#0: aborting
2020/04/21 05:49:42 [error] 9199#0: *70 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 [internal function]: think\Error::appException(Object(think\exception\ErrorException))
#5 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php on line 184PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(90): think\Error::appException(Object(think\exception\ErrorException))
#5 [internal function]: think\Error::appShutdown()
#6 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exce" while reading response header from upstream, client: 111.58.72.155, server: tc.baidu.com, request: "GET /install/index.html?step=4 HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "tc.baidu.com", referrer: "http://tc.baidu.com/install/index.html?step=3"
2020/04/21 05:49:43 [error] 9199#0: *70 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 [internal function]: think\Error::appException(Object(think\exception\ErrorException))
#5 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php on line 184PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(90): think\Error::appException(Object(think\exception\ErrorException))
#5 [internal function]: think\Error::appShutdown()
#6 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exce" while reading response header from upstream, client: 111.58.72.155, server: tc.baidu.com, request: "GET /install/index.html?step=4 HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "tc.baidu.com", referrer: "http://tc.baidu.com/install/index.html?step=3"
2020/04/21 05:49:45 [error] 9199#0: *70 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 [internal function]: think\Error::appException(Object(think\exception\ErrorException))
#5 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php on line 184PHP message: PHP Fatal error:  Uncaught think\exception\ErrorException: include(): Filename cannot be empty in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php:184
Stack trace:
#0 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): think\Error::appError(2, 'include(): File...', '/data/wwwroot/t...', 184, Array)
#1 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(184): include()
#2 /data/wwwroot/tc.baidu.com/thinkphp/library/think/exception/Handle.php(97): think\exception\Handle->convertExceptionToResponse(Object(think\exception\ErrorException))
#3 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(56): think\exception\Handle->render(Object(think\exception\ErrorException))
#4 /data/wwwroot/tc.baidu.com/thinkphp/library/think/Error.php(90): think\Error::appException(Object(think\exception\ErrorException))
#5 [internal function]: think\Error::appShutdown()
#6 {main}
  thrown in /data/wwwroot/tc.baidu.com/thinkphp/library/think/exce" while reading response header from upstream, client: 111.58.72.155, server: tc.baidu.com, request: "GET /install/index.html?step=4 HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-cgi.sock:", host: "tc.baidu.com", referrer: "http://tc.baidu.com/install/index.html?step=3"

**Comment by xingline** [comment]
我日，看了其他人的问题，原来是数据库密码不能包含特殊字符……
