### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by kuoyitung** [wisp-x/lsky-pro#183]
按照步骤将文件上传到服务器后，网页打开会提示这样的信息，求解：
Fatal error: Uncaught think\exception\ErrorException: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php:467 Stack trace: #0 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(467): think\Error::appError() #1 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(437): think\Container->bindParams() #2 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(284): think\Container->invokeClass() #3 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(132): think\Container->make() #4 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/exception/Handle.php(42): think\Container::get() #5 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Error.php(51): think\exception\Handle->report() #6 [internal function]: think\Error::appException() #7 {main} thrown in /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php on line 467

Fatal error: Uncaught think\exception\ErrorException: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php:467 Stack trace: #0 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(467): think\Error::appError() #1 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(437): think\Container->bindParams() #2 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(284): think\Container->invokeClass() #3 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php(132): think\Container->make() #4 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/exception/Handle.php(42): think\Container::get() #5 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Error.php(51): think\exception\Handle->report() #6 /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Error.php(90): think\Error::appException() #7 [internal function]: think\Error::appShutdown() #8 {main} thrown in /www/wwwroot/photos.kuo.cool/thinkphp/library/think/Container.php on line 467

**Comment by kuoyitung** [comment]
发现是php版本导致的问题
